services: 
  cliente:
    container_name: cliente
    image: alpine:latest
    tty: true
    stdin_open: true
    dns: 
      - 172.28.5.1
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.2
networks:
  bind9_subnet:
    external: true